language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t dradden/fib-finder -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dradden/fib-finder npm run test

after_success: 
  - docker build -t dradden/fib-client ./client
  - docker build -t dradden/fib-nginx ./nginx
  - docker build -t dradden/fib-server ./server
  - docker build -t dradden/fib-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push dradden/fib-client
  - docker push dradden/fib-nginx
  - docker push dradden/fib-server
  - docker push dradden/fib-worker

# deploy:
#   provider: elasticbeanstalk
#   access_key_id:
#     secure: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"
#   region: "us-east-2"
#   app: "fib-finder"
#   env: "DockerReact-env"
#   bucket_name: "elasticbeanstalk-us-east-2-655421176019"
#   bucket_path: "fib-finder"
#   on:
#     branch: master
  